allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - heic-to@1.6.5
  - miniflare@5.20261001.0-alpha
  - wrangler@4.146.0
  - baseline-browser-mapping@2.11.27
overrides:
  browserslist: ^4.29.3
  baseline-browser-mapping: ^2.11.27
  postcss: ^8.5.28
